//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public string Destination1 { get; set; }
        public string Distance { get; set; }
        public string Duration { get; set; }
    }
}
